baseURL = 'https://xiaocao.me/'
languageCode = 'en-us'
defaultContentLanguage = "en-us"
title = 'Tiny Grassland'
theme = 'tranquilpeak'
paginate = 7
canonifyurls = true

### side bar
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  pageRef = "/"
[[menu.main]]
  weight = 4
  identifier = "posts"
  name = "Posts"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-book\" aria-hidden=\"true\"></i>"
  pageRef = "/posts"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-question\" aria-hidden=\"true\"></i>"
  url = "/about"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
  url = "https://github.com/CaoeUU"

[[menu.links]]
  weight = 2
  identifier = "zhihu"
  name = "Zhihu"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-zhihu\" aria-hidden=\"true\"></i>"
  url = "https://www.zhihu.com/people/5-78-58-98/posts"


### Author
[author]
  name = "Xiaocao You"
  bio = "A Junior Student Majored in Statistics in Shanghai University of Finance and Economics"
  location = "Shanghai, China"
  picture = "images/caosmile.jpg"

### Customization
[params]
  sidebarBehavior = 1
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  coverImage = "images/background.jpg"

### Footer configuration
[params.footer]
  copyright = "<a href=\"https://github.com/CaoeUU\">XiaocaoYou</a>"