baseURL = 'https://xiaocao.me/'
languageCode = 'en-us'
title = 'Tiny Grassland'
theme = 'tranquilpeak'

### side bar
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "posts"
  name = "Posts"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-book\" aria-hidden=\"true\"></i>"
  url = "/posts"
[[menu.main]]
  weight = 3
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-question\" aria-hidden=\"true\"></i>"
  url = "/#about"

[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
  url = "https://github.com/CaoeUU"


### Author
[author]
  name = "Xiaocao You"
  bio = "A Junior Student Majored in Statistics in Shanghai University of Finance and Economics"
  location = "Shanghai, China"
  picture = "images/caosmile.jpg"

### Customization
[params]
  sidebarBehavior = 2
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  coverImage = "images/background.jpg"
  keywords = ["游小草", "Xiaocao"]